## Observations and Insights

In [8]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single dataset

# Display the data table for preview
study_results.tail(50)
#mouse_metadata

     Mouse ID  Timepoint  Tumour Volume (mm3)  Metastatic Sites
1843     m601         45            28.430964                 1
1844     d251         45            37.311236                 2
1845     a492         45            60.122011                 1
1846     x401         45            28.484033                 0
1847     p136         45            63.488697                 2
1848     c559         45            61.840058                 4
1849     s185         45            23.343598                 1
1850     i738         45            37.311846                 2
1851     i901         45            65.341811                 0
1852     c757         45            69.042841                 3
1853     t724         45            75.113288                 2
1854     s710         45            40.728578                 1
1855     x581         45            64.634949                 3
1856     a275         45            62.999356                 3
1857     a520         45            38.810366                 1
1858     k210         45            68.923185                 3
1859     j119         45            38.125164                 1
1860     y478         45            66.842635                 1
1861     l725         45            76.668817                 3
1862     x822         45            61.386660                 3
1863     l700         45            63.946640                 1
1864     l733         45            64.299830                 1
1865     n304         45            63.586395                 4
1866     o795         45            73.059454                 4
1867     u196         45            40.667713                 3
1868     r604         45            62.670759                 3
1869     z969         45            73.867845                 4
1870     g791         45            29.128472                 1
1871     i635         45            58.633404                 3
1872     o287         45            59.741901                 4
1873     r701         45            69.778544                 1
1874     r811         45            37.225650                 1
1875     u327         45            66.268801                 2
1876     s565         45            72.588964                 2
1877     g570         45            70.492788                 2
1878     i557         45            47.685963                 1
1879     a644         45            32.978522                 1
1880     j755         45            69.563621                 1
1881     e213         45            63.105696                 4
1882     e584         45            68.359777                 4
1883     t718         45            63.423695                 4
1884     o562         45            72.455421                 2
1885     i177         45            33.562402                 3
1886     v991         45            70.167749                 4
1887     z795         45            65.741070                 3
1888     r944         45            41.581521                 2
1889     u364         45            31.023923                 3
1890     p438         45            61.433892                 1
1891     x773         45            58.634971                 4
1892     b879         45            72.555239                 2

In [2]:
# Checking the number of mice.

In [3]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint.

In [4]:
# Optional: Get all the data for the duplicate mouse ID.

In [5]:
# Create a clean DataFrame by dropping the duplicate mouse by its ID.

In [6]:
# Checking the number of mice in the clean DataFrame.

## Summary Statistics

In [7]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumour volume for each regimen

# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumour volume. 
# Assemble the resulting series into a single summary dataframe.

In [8]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumour volume for each regimen

# Using the aggregation method, produce the same summary statistics in a single line

## Bar and Pie Charts

In [9]:
# Generate a bar plot showing the total number of timepoints for all mice tested for each drug regimen using Pandas.

In [10]:
# Generate a bar plot showing the total number of timepoints for all mice tested for each drug regimen using pyplot.

In [11]:
# Generate a pie plot showing the distribution of female versus male mice using Pandas

In [12]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [13]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original dataframe to get the tumour volume at the last timepoint

In [14]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumour vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumour volumes
    
    
    # add subset 
    
    
    # Determine outliers using upper and lower bounds

In [15]:
# Generate a box plot of the final tumour volume of each mouse across four regimens of interest

## Line and Scatter Plots

In [16]:
# Generate a line plot of tumour volume vs. time point for a mouse treated with Capomulin

In [17]:
# Generate a scatter plot of average tumour volume vs. mouse weight for the Capomulin regimen

## Correlation and Regression

In [18]:
# Calculate the correlation coefficient and linear regression model 
# for mouse weight and average tumour volume for the Capomulin regimen